package com.freetime.sdk.payment

enum class PaymentError {
    INVALID_AMOUNT,
    INVALID_CURRENCY,
    NETWORK_ERROR,
    INSUFFICIENT_FUNDS,
    TRANSACTION_FAILED,
    TIMEOUT,
    INVALID_ADDRESS,
    INVALID_PRIVATE_KEY,
    API_ERROR,
    AUTHENTICATION_FAILED,
    RATE_LIMIT_EXCEEDED,
    UNKNOWN_ERROR
}
